### ISSUE TITLE
tar.Extract is not a function

### ISSUE THREAD

**Issue by pacs** [apigee-127/a127-documentation#15]
```
    .pipe(tar.Extract({ path: directory }))
              ^

TypeError: tar.Extract is not a function
    at inflate (/usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:133:15)
    at /usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:77:5
    at /usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:123:11
    at FSReqWrap.oncomplete (fs.js:114:15)
```
The New tar seems to not have the needed function could you restrict ist to the 2 Version ?

**Comment by Technisiums** [comment]
Hi, have you found any solution to this error?
if yes, please help me, thanks

> ```
>     .pipe(tar.Extract({ path: directory }))
>               ^
> 
> TypeError: tar.Extract is not a function
>     at inflate (/usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:133:15)
>     at /usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:77:5
>     at /usr/lib/node_modules/apigee-127/node_modules/usergrid-installer/lib/download.js:123:11
>     at FSReqWrap.oncomplete (fs.js:114:15)
> ```
> The New tar seems to not have the needed function could you restrict ist to the 2 Version ?

**Comment by pacs** [comment]
sry - at the time i was playing around with baas to test the different solutions that exists.
i belive i adjusted the json ? and manualy set a previous version of the tar module ?
